events {}
http {
  server {
    listen 8080;

    location / {
      proxy_pass https://m3mobile-manual.refined.site/;
      proxy_set_header Host m3mobile-manual.refined.site;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Accept-Encoding "";
      proxy_ssl_server_name on;
    }
  }
}
